apiVersion: batch/v1
kind: CronJob
metadata:
  name: jira-backup
spec:
  schedule: "5 2 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: ghcr.io/eumel8/jira-backup/jira-backup:latest
            imagePullPolicy: Always
            env:
            - name: JIRA_BASE_URL
              value: "https://jira.example.com"
            - name: JIRA_SPACE_KEY
              value: "MYSPACE"
            - name: JIRA_TOKEN
              value: ""
            resources:
              limits:
                cpu: 500m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
                - CAP_NET_RAW
              privileged: false
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
              seccompProfile:
                type: RuntimeDefault
            volumeMounts:
            - mountPath: /data
              name: jira-data
            - name: tmp
              mountPath: /tmp
            #- name: config
            #  mountPath: /config
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            supplementalGroups:
            - 1000
            seccompProfile:
              type: RuntimeDefault
          volumes:
          - name: jira-data
            persistentVolumeClaim:
              claimName: jira-data
          - name: tmp
            emptyDir:
              sizeLimit: 1000Mi
          #- name: config
          #  secret:
          #    secretName: jira-config
          #    items:
          #    - key: config.json
          #      path: config.json
